defaults:
  - model: default
  - dataset: unbiased_classification
  - embedding: default
  - _self_

run_name: ${now:%Y-%m-%d_%H-%M-%S}
batch_size: 256
num_epochs: 1000
lr: 1e-4
weight_decay: 1e-6
eval_freq: 10
chkpt_freq: 100
patience: -1
wandb: false
verbose: false
sweep_id: null

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
